### ISSUE TITLE
Random public port range should be split in two attributes: star & end

### ISSUE THREAD

**Issue by miguelaferreira** [MissionCriticalCloud/vagrant-cloudstack#114]
This way we could better integrate with other tools (kitchen e.g.)

**Comment by bheuvel** [comment]
When using the latest PR created  at kitchen-vagrant https://github.com/test-kitchen/kitchen-vagrant/pull/167 ;

``` YAML
    pf_public_port_randomrange:
      start: 49160
      end: 49200
```

resulting/requested Vagrantfile:

``` ruby
pf_public_port_randomrange = {:start=>49160, :end=>49200}
```
